### ISSUE TITLE
[Anon] Bug report: Space Marines - Space Wolves - EA.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-epic-armageddon#1]
**File:** Space Marines - Space Wolves - EA.catz

**BattleScribe version:** 1.15.07

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** What's broken:
- error will shows "Space Marines: Space Wolves (Epic Armageddon) has 1 too many selections of Long Fangs Pack (maximum 0)" once you add Long Fangs Pack to army list

What's correct:
- this error should not be shown because there is no option selected when it is added to army list;

**Comment by afraeve** [comment]
Hi, please be sure to select your Group before adding other items to the roster. Once you've done that (the default group is NetEA) and added a Long Fangs Pack, you will also receive an error asking you to add a Great Company. Adding this will clear the error message, as you may have 1 Long Fangs Pack per Great Company.

If you select F-ERC as your Group, then their shouldn't be any error message.
