### ISSUE TITLE
[Anon] Bug report: Imperial Guard - Minervan Tank Legion - EA.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-epic-armageddon#10]
**File:** Imperial Guard - Minervan Tank Legion - EA.catz

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** No

**Description:** Hi, there is a mistake with the cost of the vanquisher. True cost is 45, mistaken cost 20

**Comment by afraeve** [comment]
Thanks
