### ISSUE TITLE
[Anon] Bug report: Imperial Guard - Harakoni Warhawks - EA.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-epic-armageddon#11]
**File:** Imperial Guard - Harakoni Warhawks - EA.catz

**BattleScribe version:** 2.03.00

**Platform:** Android

**Dropbox:** No

**Description:** The Forward Observer option yields an error message no matter where I choose it.

**Comment by afraeve** [comment]
Thanks for reporting. It was set to 0-1 per 2000pts min - I've changed that to round up to 2000pts
