### ISSUE TITLE
[Anon] Bug report: Necrons - Sautekh Legion - EA.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-epic-armageddon#12]
**File:** Necrons - Sautekh Legion - EA.catz

**BattleScribe version:** 2.03.13

**Platform:** Windows

**Dropbox:** Yes

**Description:** The Necron Sautekh Legion list does not meet the current Necron Sautekh Legion v1.1 list.
The following formations should automatically come with a Necron Lord, and have the option to add a cryptek for an additional 50 points and replace the lord with an overlord for +75 points: warrior phalanx, ghost ark phalanx and immortal phalanx. The Triarch phalanx allows you to purchase an additional triarch praetorian, or a lord for +25 points, add a cryptek for 50 points, and replace the lord for an overlord for +75 points.

**Comment by afraeve** [comment]
The Triarch phalanx allows you to add a Lord to a triarch praetorian for 25pts and add 2x triarch praetorians for 125pts. The other options you mention are all available
![necrons](https://user-images.githubusercontent.com/13020665/77947910-82acc400-72bc-11ea-85a8-a39bf0ae0c90.jpg)

Please update to BattleScribe version 2.03.14 - I think there were some bugs in 2.03.13
