### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by CygnusMaya** [BSData/wh40k-epic-armageddon#13]
I’d like to attempt to add a experimental list we are working on. 

I have limited experience, and it’s feeling more and more daunting, but I’ve downloaded (i think) everything I need, now its s mattet of figuranter out how to create , Edit and upload the stuff

**Comment by afraeve** [comment]
Hi, I'm always glad to hear someone actually uses these, I've had very little feedback. What list are you working on? I've been trying to stick to the published pdfs from the main forums to avoid things getting swamped - 335 files is a lot to keep track of!

**Comment by afraeve** [comment]
Closed because there was no reply
