### ISSUE TITLE
[Anon] Bug report: Imperial Guard - Armageddon Ork Hunters - EA.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-epic-armageddon#14]
**File:** Imperial Guard - Armageddon Ork Hunters - EA.catz

**BattleScribe version:** 2.03.18

**Platform:** Windows

**Dropbox:** No

**Description:** All the imperial Guard and the vraksian renegades lists bring an error up when oyu select the commissar/enforcer.  You are allowed 1 free commissar.Enforcer (in the case of the Vraksian list) for every 500 points of your army. The first has to be added to the regimental command, the rest added as you wish.  This appears to be an error in all the listsfrom the standard guard, cadians, catachans, minervans, etc.

**Comment by afraeve** [comment]
Hi, thanks for your feedback. I've tried each of the lists you mention, but am unable to reproduce the error. I've also checked them on Android.
The data editor appears to be buggy, though, so I'm looking at raising an issue with the developer.

**Comment by afraeve** [comment]
I wasn't getting any error because most of the files didn't have the necessary code - have added that now, will publish a release in next few days
