### ISSUE TITLE
[Anon] Bug report: Chaos - Vraks - EA.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-epic-armageddon#15]
**File:** Chaos - Vraks - EA.catz

**BattleScribe version:** 2.03.20

**Platform:** Windows

**Dropbox:** No

**Description:** Vraksians are allowed 1 free commissar for every 500 points of the army.  Your list does not allow even one commisar, let alone 0ne for every 500 points.

**Comment by afraeve** [comment]
It seems to be working fine for me. Am I missing something?

![vra](https://user-images.githubusercontent.com/13020665/82757698-193bc400-9dda-11ea-8440-3618af98eb1e.jpg)
