### ISSUE TITLE
[Anon] Bug report: Imperial Guard - Elysian Drop Troops - EA.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-epic-armageddon#16]
**File:** Imperial Guard - Elysian Drop Troops - EA.catz

**BattleScribe version:** 2.03.20

**Platform:** Windows

**Dropbox:** No

**Description:** I see the problem with the commissar has been fixed with a lot of the imperial guard list. However this list still needs the error fixed.  I will not allow commissars to be added, without reporting a fault.

**Comment by afraeve** [comment]
It seems to be working fine for me. Am I missing something?

![ely](https://user-images.githubusercontent.com/13020665/82757694-12ad4c80-9dda-11ea-8312-465959ead020.jpg)
