### ISSUE TITLE
[Anon] Bug report: Imperial Guard - Harakoni Warhawks - EA.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-epic-armageddon#17]
**File:** Imperial Guard - Harakoni Warhawks - EA.catz

**BattleScribe version:** 2.03.20

**Platform:** Windows

**Dropbox:** No

**Description:** Will not allows commissars without an error. Will not allow forward observers without an error.

**Comment by afraeve** [comment]
It seems to be working fine for me. Am I missing something?

![har](https://user-images.githubusercontent.com/13020665/82757677-fd382280-9dd9-11ea-86be-d0a8e68701ac.jpg)
