### ISSUE TITLE
BattleScribe 2.0

### ISSUE THREAD

**Issue by Jonskichov** [BSData/wh40k-epic-armageddon#2]
Hi guys.

BattleScribe 2.0 is coming and it contains some major changes to Data Editor and the data format.

While it should happily upgrade 1.15.x format data files to the new format, you never know what sneaky bugs might be lurking...

It would help a lot if you could run your data through it and make sure nothing gets broken so we have no nasty surprises on release day (whenever that might be...).

**Alpha Downloads:**
Desktop: https://github.com/BattleScribe/Desktop-Alphas/issues/1
Android: https://github.com/BattleScribe/Android-Alphas/issues/1
iOS: https://github.com/BattleScribe/iOS-Alphas/issues/1

If you find any issues, please do let me know: https://github.com/BattleScribe/Desktop-Alphas/issues

**Comment by afraeve** [comment]
[x] All files updated to BS 2.0 format, version numbers bumped by 1.
There was only a single broken link across all 105 .cat files, which is pretty impressive. Next step is to go through them all in the roster editor to hunt for obvious errors - suspect there will be more than a few thrown up by the way min/max selections are now a thing that affects root level entries.

**Comment by Jonskichov** [comment]
@afraeve 

Sounds like you're getting along fine! Let me know if you need anything.

**Comment by afraeve** [comment]
Thanks @Jonskichov - I knocked these together when I was ill & out of work; now I'm finally back working again... and there are 239 forces to error check...

Nah, all I really need is time, _and maybe for the Tactical Command guys to take a day off._
