### ISSUE TITLE
[Anon] Bug report: Horus Heresy - Legiones Astartes - EA.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-epic-armageddon#21]
**File:** Horus Heresy - Legiones Astartes - EA.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Droppod option isn’t accepted as a viable transport option. No matter the circumstance, even putting a line detachment with just tactical squads and no other upgrades, does it accept the option, let alone things like the dreadnoughts

**Comment by afraeve** [comment]
I dunno why I thought Drop Pods couldn't carry Dreadnoughts. Fixed. Remember to take a Spacecraft.
