### ISSUE TITLE
[Anon] Bug report: Imperial Guard - Elysian Drop Troops - EA.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-epic-armageddon#22]
**File:** Imperial Guard - Elysian Drop Troops - EA.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Hi ! Thanks for your amazing work !
I'm just participating by reporting a bug in the Elysian f-erc list.
Airborne multi-meta sentinels are 100pts and Support multiple rocket launcher ones are 150pts.
I posted a link to your work on the french epic forum, epic_fr. If we can contribute in any way to your project, we'd be glad to help.
Baptiste, from Paris, France

**Comment by afraeve** [comment]
Merci Baptiste!
I haven't joined the forum because I don't speak enough French - you can probably see that from the rules I translated - but I joined the discord server a few days ago
