### ISSUE TITLE
[Anon] Bug report: Adeptus Mechanicus - Titan Legions - EA.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-epic-armageddon#25]
**File:** Adeptus Mechanicus - Titan Legions - EA.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** For NetEA group, Forge Knight Maniple costs 150 and NetEA Tournament Pack says that the cost is 250.

**Comment by afraeve** [comment]
Thanks for the spot! I will roll that into the next release - working on the skitarii just now, so will get both out at the same time.
