### ISSUE TITLE
[Anon] Bug report: Necrons - EA.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-epic-armageddon#28]
**File:** Necrons - EA.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Hi ! :)
About the Army of the Aeons f-erc army list, the character points are all overpriced.
Tetrarque is 100pts in battlescribe but shoud be 75
Cryptek should be 50 instead of 75
Dynast should be 25 instead of 50.

The Immortal Phalanx should be 275pts instead of 250. Thank you for all your work ! baptiste
source : https://www.epicarmageddon.fr/

**Comment by afraeve** [comment]
Thanks! Sorry for the late reply. The characters are correct - Warriors & Immortals must buy a Command Barge (+25pts) to have a lord. I've fixed the price of the Immortal Phalanx & will upload an update soon.
