### ISSUE TITLE
[Anon] Bug report: Space Marines - EA.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-epic-armageddon#3]
**File:** Space Marines - EA.catz

**BattleScribe version:** 1.15.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The unit costs for various units seems very off from the list. Terminators for example should be 325 points and are 400 in the repository.

**Comment by afraeve** [comment]
I'm not able to replicate that on Windows or Android - the Terminators show up with the correct pts value.

These files rely heavily on the ability to hide and/or modify units depending on which group (eg: NetEA, EpicUK, etc) you select. I've been told that this doesn't work correctly on the current Apple version of BattleScribe but I don't own an iPhone or iPad to confirm that.

The good news is BattleScribe 2.0 is due in a few weeks & that should sort it.
