### ISSUE TITLE
[Anon] Bug report: Space Marines - Blood Angels - EA.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-epic-armageddon#4]
**File:** Space Marines - Blood Angels - EA.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** Assault Squad should be 85pts with jump-packs standard and dedicated transports free if the jp's are removed - this data file (as with HoR and standard 40k files) does not allow for this...

Points need to be rechecked and options need to be recalculated...

**Comment by afraeve** [comment]
That's a 40k query, not Epic Armageddon, so I've reposted your issue over there:
https://github.com/BSData/wh40k/issues/2549
