### ISSUE TITLE
[Anon] Bug report: Chaos - Death Guard - EA.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-epic-armageddon#6]
**File:** Chaos - Death Guard - EA.catz

**BattleScribe version:** 2.01.10

**Platform:** Windows

**Dropbox:** No

**Description:** Nurglings and plaguebearers are missing from troop choices. The Plague Brethren is just a special box set, not a unit choice (they are just plague marines).  Beasts of Nurgle us missing from elite choices. Plague drones missing from fast attack choices.  All of these missing unites are available in the Death Guard codex.

**Comment by afraeve** [comment]
Apologies for the late response, I haven't been following developments in the last year.

The BS2.01 update stripped out support for html tags, which stops the profiles displaying correctly. It also seems to have borked the ways pts are calculated.
At a rough estimate I'd be looking at 3-600hrs work to get everything back up and running, *if* I could figure a way to display the weapon stats... 

I can't justify putting that kind of time to put into it, so I'm not sure if the repo will be updated further.

**Comment by afraeve** [comment]
40k bug...
