### ISSUE TITLE
[Anon] Bug report: Orks - Ghazghkull Thraka's War Horde - EA.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-epic-armageddon#7]
**File:** Orks - Ghazghkull Thraka's War Horde - EA.catz

**BattleScribe version:** 2.01.20

**Platform:** Android

**Dropbox:** No

**Description:** In the "mek's stompamob" you can't select the size of the formation, onlt appears the opción of "normal", instead of having the options "normal", "Big" or "huge".

**Comment by afraeve** [comment]
Got to the **-Community-** entry and change your Group to **NetEA** if you're using the netea-tournament-pack-2018-06-07.pdf, or **F-ERC** if you're using the FERC_ORK.pdf. Both these lists have big or huge options for the stompamob, while the GW and EpicUK lists only have the normal size.
You can also select the language there.
