### ISSUE TITLE
[Anon] Bug report: Space Marines - Imperial Fists - EA.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-epic-armageddon#9]
**File:** Space Marines - Imperial Fists - EA.catz

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** No

**Description:** Hi, 2 details:

There is a mistake with the prices of :

Terminators , must be changed from 225 points to 325 points
Landspeeders, the upgrade to typhoon must be 10 points instead of the 25. Cheers!!!

**Comment by afraeve** [comment]
Thanks
